db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_ROOT_PASSWORD: ""
  volumes:
   - ..:/home
  command: bash -c "cd home/python_vul_app && service mysql start && mysql < db/db.sql"

myapp:
  build: .
  ports:
    - 5000:5000
  links:
   - db
